name: Rules test

on: push    
jobs:
  rules-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Downloads clj-holmes
        run: curl -L https://github.com/clj-holmes/clj-holmes/releases/latest/download/clj-holmes-ubuntu-latest -o /tmp/clj-holmes && chmod +x /tmp/clj-holmes

      - name: validate rules specs
        run: /tmp/clj-holmes validate-rules -d .

      - name: check if rules are working as expected
        run: find . -type f -name \*.yml  -not -path '*/\.*' | xargs -I {} bash scripts/test-rules.sh {}
